In [1]:
import pandas as pd
import numpy as np

In [2]:
edata =[
    [100,'Tom','Mgr',2500],
    [200,'Mary','Pgmr',3700],
    [300,'Kate','HR',4200],
    [400,'Tim', 'Mgr', 3200],
    [500,'Jon','Pgmr',6400],
    [600,'William','HR', 4700]
]

In [3]:
e1 = pd.DataFrame(edata)
e1

     0        1     2     3
0  100      Tom   Mgr  2500
1  200     Mary  Pgmr  3700
2  300     Kate    HR  4200
3  400      Tim   Mgr  3200
4  500      Jon  Pgmr  6400
5  600  William    HR  4700

In [4]:
type(e1)

pandas.DataFrame

In [5]:
e2 = pd.DataFrame(edata, 
                      columns=['eid','ename','job','salary'])
e2

   eid    ename   job  salary
0  100      Tom   Mgr    2500
1  200     Mary  Pgmr    3700
2  300     Kate    HR    4200
3  400      Tim   Mgr    3200
4  500      Jon  Pgmr    6400
5  600  William    HR    4700

In [6]:
edf = pd.DataFrame(edata, 
                       columns=['eid','ename','job','salary'], 
                       index=['e1','e2','e3','e4','e5','e6'])
edf

    eid    ename   job  salary
e1  100      Tom   Mgr    2500
e2  200     Mary  Pgmr    3700
e3  300     Kate    HR    4200
e4  400      Tim   Mgr    3200
e5  500      Jon  Pgmr    6400
e6  600  William    HR    4700

#### Accessing Data

In [7]:
edf.iloc[:,1]

e1        Tom
e2       Mary
e3       Kate
e4        Tim
e5        Jon
e6    William
Name: ename, dtype: str

In [8]:
edf.loc[:,'ename']

e1        Tom
e2       Mary
e3       Kate
e4        Tim
e5        Jon
e6    William
Name: ename, dtype: str

In [9]:
edf.iloc[:,1:3]

      ename   job
e1      Tom   Mgr
e2     Mary  Pgmr
e3     Kate    HR
e4      Tim   Mgr
e5      Jon  Pgmr
e6  William    HR

In [10]:
edf.iloc[:,:3]

    eid    ename   job
e1  100      Tom   Mgr
e2  200     Mary  Pgmr
e3  300     Kate    HR
e4  400      Tim   Mgr
e5  500      Jon  Pgmr
e6  600  William    HR

In [11]:
edf.loc[:,'ename':'job']

      ename   job
e1      Tom   Mgr
e2     Mary  Pgmr
e3     Kate    HR
e4      Tim   Mgr
e5      Jon  Pgmr
e6  William    HR

In [12]:
edf.loc[:,:'job']

    eid    ename   job
e1  100      Tom   Mgr
e2  200     Mary  Pgmr
e3  300     Kate    HR
e4  400      Tim   Mgr
e5  500      Jon  Pgmr
e6  600  William    HR

In [13]:
edf.iloc[:,[1,3]]

      ename  salary
e1      Tom    2500
e2     Mary    3700
e3     Kate    4200
e4      Tim    3200
e5      Jon    6400
e6  William    4700

In [14]:
edf.loc[:,['ename','salary']]

      ename  salary
e1      Tom    2500
e2     Mary    3700
e3     Kate    4200
e4      Tim    3200
e5      Jon    6400
e6  William    4700

#### shortcuts for columns

In [15]:
edf['ename']

e1        Tom
e2       Mary
e3       Kate
e4        Tim
e5        Jon
e6    William
Name: ename, dtype: str

In [16]:
edf[['ename','salary']]

      ename  salary
e1      Tom    2500
e2     Mary    3700
e3     Kate    4200
e4      Tim    3200
e5      Jon    6400
e6  William    4700

In [17]:
type(edf['ename'])

pandas.Series

#### Accessing Columns

In [18]:
edf.iloc[1,:]

eid        200
ename     Mary
job       Pgmr
salary    3700
Name: e2, dtype: object

In [19]:
# shortcut
edf.iloc[1]

eid        200
ename     Mary
job       Pgmr
salary    3700
Name: e2, dtype: object

In [20]:
edf.loc['e2',:]

eid        200
ename     Mary
job       Pgmr
salary    3700
Name: e2, dtype: object

In [21]:
# Shortcut
edf.loc['e2']

eid        200
ename     Mary
job       Pgmr
salary    3700
Name: e2, dtype: object

In [22]:
edf.iloc[[1,3,5],:]

    eid    ename   job  salary
e2  200     Mary  Pgmr    3700
e4  400      Tim   Mgr    3200
e6  600  William    HR    4700

In [23]:
# Shortcut
edf.iloc[[1,3,5]]

    eid    ename   job  salary
e2  200     Mary  Pgmr    3700
e4  400      Tim   Mgr    3200
e6  600  William    HR    4700

In [24]:
edf.loc[['e4','e2','e5'],:]

    eid ename   job  salary
e4  400   Tim   Mgr    3200
e2  200  Mary  Pgmr    3700
e5  500   Jon  Pgmr    6400

In [25]:
# Shortcut
edf.loc[['e4','e2','e5']]

    eid ename   job  salary
e4  400   Tim   Mgr    3200
e2  200  Mary  Pgmr    3700
e5  500   Jon  Pgmr    6400

In [26]:
edf.iloc[1:5,:]

    eid ename   job  salary
e2  200  Mary  Pgmr    3700
e3  300  Kate    HR    4200
e4  400   Tim   Mgr    3200
e5  500   Jon  Pgmr    6400

In [27]:
edf.iloc[1:5]

    eid ename   job  salary
e2  200  Mary  Pgmr    3700
e3  300  Kate    HR    4200
e4  400   Tim   Mgr    3200
e5  500   Jon  Pgmr    6400

In [28]:
edf.iloc[:5]

    eid ename   job  salary
e1  100   Tom   Mgr    2500
e2  200  Mary  Pgmr    3700
e3  300  Kate    HR    4200
e4  400   Tim   Mgr    3200
e5  500   Jon  Pgmr    6400

In [29]:
edf.iloc[2:]

    eid    ename   job  salary
e3  300     Kate    HR    4200
e4  400      Tim   Mgr    3200
e5  500      Jon  Pgmr    6400
e6  600  William    HR    4700

In [30]:
edf.loc['e2':'e5',:]

    eid ename   job  salary
e2  200  Mary  Pgmr    3700
e3  300  Kate    HR    4200
e4  400   Tim   Mgr    3200
e5  500   Jon  Pgmr    6400

In [31]:
# Shortcut
edf.loc['e2':'e5']

    eid ename   job  salary
e2  200  Mary  Pgmr    3700
e3  300  Kate    HR    4200
e4  400   Tim   Mgr    3200
e5  500   Jon  Pgmr    6400

In [32]:
# Shortcut
edf.loc[:'e5']

    eid ename   job  salary
e1  100   Tom   Mgr    2500
e2  200  Mary  Pgmr    3700
e3  300  Kate    HR    4200
e4  400   Tim   Mgr    3200
e5  500   Jon  Pgmr    6400

In [33]:
# Shortcut
edf.loc['e3':]

    eid    ename   job  salary
e3  300     Kate    HR    4200
e4  400      Tim   Mgr    3200
e5  500      Jon  Pgmr    6400
e6  600  William    HR    4700

#### Load data from external file

In [34]:
univ = pd.read_csv('Universities.csv')
univ

            Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
0          Brown  1310     89      22       13     22704        94
1        CalTech  1415    100      25        6     63575        81
2            CMU  1260     62      59        9     25026        72
3       Columbia  1310     76      24       12     31510        88
4        Cornell  1280     83      33       13     21864        90
5      Dartmouth  1340     89      23       10     32162        95
6           Duke  1315     90      30       12     31585        95
7     Georgetown  1255     74      24       12     20126        92
8        Harvard  1400     91      14       11     39525        97
9   JohnsHopkins  1305     75      44        7     58691        87
10           MIT  1380     94      30       10     34870        91
11  Northwestern  1260     85      39       11     28052        89
12     NotreDame  1255     81      42       13     15122        94
13     PennState  1081     38      54       18     10185        80
14     Princeton  1375     91      14        8     30220        95
15        Purdue  1005     28      90       19      9066        69
16      Stanford  1360     90      20       12     36450        93
17      TexasA&M  1075     49      67       25      8704        67
18    UCBerkeley  1240     95      40       17     15140        78
19      UChicago  1290     75      50       13     38380        87
20     UMichigan  1180     65      68       16     15470        85
21         UPenn  1285     80      36       11     27553        90
22           UVA  1225     77      44       14     13349        92
23    UWisconsin  1085     40      69       15     11857        71
24          Yale  1375     95      19       11     43514        96

In [35]:
univ.iloc[6:10]

           Univ   SAT  Top10  Accept  SFRatio  Expenses  GradRate
6          Duke  1315     90      30       12     31585        95
7    Georgetown  1255     74      24       12     20126        92
8       Harvard  1400     91      14       11     39525        97
9  JohnsHopkins  1305     75      44        7     58691        87

In [36]:
udf = pd.read_csv('Universities.csv', index_col='Univ')
udf

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown         1310     89      22       13     22704        94
CalTech       1415    100      25        6     63575        81
CMU           1260     62      59        9     25026        72
Columbia      1310     76      24       12     31510        88
Cornell       1280     83      33       13     21864        90
Dartmouth     1340     89      23       10     32162        95
Duke          1315     90      30       12     31585        95
Georgetown    1255     74      24       12     20126        92
Harvard       1400     91      14       11     39525        97
JohnsHopkins  1305     75      44        7     58691        87
MIT           1380     94      30       10     34870        91
Northwestern  1260     85      39       11     28052        89
NotreDame     1255     81      42       13     15122        94
PennState     1081     38      54       18     10185        80
Princeton     1375     91      14        8     30220        95
Purdue        1005     28      90       19      9066        69
Stanford      1360     90      20       12     36450        93
TexasA&M      1075     49      67       25      8704        67
UCBerkeley    1240     95      40       17     15140        78
UChicago      1290     75      50       13     38380        87
UMichigan     1180     65      68       16     15470        85
UPenn         1285     80      36       11     27553        90
UVA           1225     77      44       14     13349        92
UWisconsin    1085     40      69       15     11857        71
Yale          1375     95      19       11     43514        96

In [37]:
udf.loc['Duke':'MIT']

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Duke          1315     90      30       12     31585        95
Georgetown    1255     74      24       12     20126        92
Harvard       1400     91      14       11     39525        97
JohnsHopkins  1305     75      44        7     58691        87
MIT           1380     94      30       10     34870        91

In [38]:
udf.loc['Stanford']

SAT          1360
Top10          90
Accept         20
SFRatio        12
Expenses    36450
GradRate       93
Name: Stanford, dtype: int64

In [39]:
udf.loc['Duke':'MIT', 'Top10':'SFRatio']

              Top10  Accept  SFRatio
Univ
Duke             90      30       12
Georgetown       74      24       12
Harvard          91      14       11
JohnsHopkins     75      44        7
MIT              94      30       10

In [40]:
udf.loc['Duke','Accept']

np.int64(30)

#### Accessing Data based on conditions

In [41]:
udf['Expenses'] >= 35000

Univ
Brown           False
CalTech          True
CMU             False
Columbia        False
Cornell         False
Dartmouth       False
Duke            False
Georgetown      False
Harvard          True
JohnsHopkins     True
MIT             False
Northwestern    False
NotreDame       False
PennState       False
Princeton       False
Purdue          False
Stanford         True
TexasA&M        False
UCBerkeley      False
UChicago         True
UMichigan       False
UPenn           False
UVA             False
UWisconsin      False
Yale             True
Name: Expenses, dtype: bool

In [42]:
udf[ udf['Expenses'] >= 35000 ]

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
CalTech       1415    100      25        6     63575        81
Harvard       1400     91      14       11     39525        97
JohnsHopkins  1305     75      44        7     58691        87
Stanford      1360     90      20       12     36450        93
UChicago      1290     75      50       13     38380        87
Yale          1375     95      19       11     43514        96

In [43]:
# Universities with Graduation Rate < 70 %
udf[ udf['GradRate'] < 70]

           SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Purdue    1005     28      90       19      9066        69
TexasA&M  1075     49      67       25      8704        67

In [44]:
(udf['SAT'] >1200) & (udf['Expenses'] < 50000)

Univ
Brown            True
CalTech         False
CMU              True
Columbia         True
Cornell          True
Dartmouth        True
Duke             True
Georgetown       True
Harvard          True
JohnsHopkins    False
MIT              True
Northwestern     True
NotreDame        True
PennState       False
Princeton        True
Purdue          False
Stanford         True
TexasA&M        False
UCBerkeley       True
UChicago         True
UMichigan       False
UPenn            True
UVA              True
UWisconsin      False
Yale             True
dtype: bool

In [45]:
udf[(udf['SAT'] >1200) & (udf['Expenses'] < 30000)]

               SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown         1310     89      22       13     22704        94
CMU           1260     62      59        9     25026        72
Cornell       1280     83      33       13     21864        90
Georgetown    1255     74      24       12     20126        92
Northwestern  1260     85      39       11     28052        89
NotreDame     1255     81      42       13     15122        94
UCBerkeley    1240     95      40       17     15140        78
UPenn         1285     80      36       11     27553        90
UVA           1225     77      44       14     13349        92

#### Attributes of Dataframe

In [46]:
univ.columns

Index(['Univ', 'SAT', 'Top10', 'Accept', 'SFRatio', 'Expenses', 'GradRate'], dtype='str')

In [47]:
udf.columns

Index(['SAT', 'Top10', 'Accept', 'SFRatio', 'Expenses', 'GradRate'], dtype='str')

In [48]:
edf.columns

Index(['eid', 'ename', 'job', 'salary'], dtype='str')

In [49]:
univ.index

RangeIndex(start=0, stop=25, step=1)

In [50]:
udf.index

Index(['Brown', 'CalTech', 'CMU', 'Columbia', 'Cornell', 'Dartmouth', 'Duke',
       'Georgetown', 'Harvard', 'JohnsHopkins', 'MIT', 'Northwestern',
       'NotreDame', 'PennState', 'Princeton', 'Purdue', 'Stanford', 'TexasA&M',
       'UCBerkeley', 'UChicago', 'UMichigan', 'UPenn', 'UVA', 'UWisconsin',
       'Yale'],
      dtype='str', name='Univ')

In [51]:
edf.index

Index(['e1', 'e2', 'e3', 'e4', 'e5', 'e6'], dtype='str')

In [52]:
univ.shape

(25, 7)

In [53]:
udf.shape

(25, 6)

In [54]:
edf.shape

(6, 4)

#### Methods of Dataframe

#### Examine the data

In [55]:
# Default 5 rows
udf.head()

           SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown     1310     89      22       13     22704        94
CalTech   1415    100      25        6     63575        81
CMU       1260     62      59        9     25026        72
Columbia  1310     76      24       12     31510        88
Cornell   1280     83      33       13     21864        90

In [56]:
udf.head(3)

          SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown    1310     89      22       13     22704        94
CalTech  1415    100      25        6     63575        81
CMU      1260     62      59        9     25026        72

In [57]:
udf.tail()

             SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
UMichigan   1180     65      68       16     15470        85
UPenn       1285     80      36       11     27553        90
UVA         1225     77      44       14     13349        92
UWisconsin  1085     40      69       15     11857        71
Yale        1375     95      19       11     43514        96

In [58]:
udf.tail(3)

             SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
UVA         1225     77      44       14     13349        92
UWisconsin  1085     40      69       15     11857        71
Yale        1375     95      19       11     43514        96

In [59]:
udf.info()

<class 'pandas.DataFrame'>
Index: 25 entries, Brown to Yale
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   SAT       25 non-null     int64
 1   Top10     25 non-null     int64
 2   Accept    25 non-null     int64
 3   SFRatio   25 non-null     int64
 4   Expenses  25 non-null     int64
 5   GradRate  25 non-null     int64
dtypes: int64(6)
memory usage: 2.1 KB

In [60]:
udf.describe()

               SAT       Top10     Accept   SFRatio      Expenses   GradRate
count    25.000000   25.000000  25.000000  25.00000     25.000000  25.000000
mean   1266.440000   76.480000  39.200000  12.72000  27388.000000  86.720000
std     108.359771   19.433905  19.727308   4.06735  14424.883165   9.057778
min    1005.000000   28.000000  14.000000   6.00000   8704.000000  67.000000
25%    1240.000000   74.000000  24.000000  11.00000  15140.000000  81.000000
50%    1285.000000   81.000000  36.000000  12.00000  27553.000000  90.000000
75%    1340.000000   90.000000  50.000000  14.00000  34870.000000  94.000000
max    1415.000000  100.000000  90.000000  25.00000  63575.000000  97.000000

#### Check for nulls

In [61]:
udf.isna()

                SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ
Brown         False  False   False    False     False     False
CalTech       False  False   False    False     False     False
CMU           False  False   False    False     False     False
Columbia      False  False   False    False     False     False
Cornell       False  False   False    False     False     False
Dartmouth     False  False   False    False     False     False
Duke          False  False   False    False     False     False
Georgetown    False  False   False    False     False     False
Harvard       False  False   False    False     False     False
JohnsHopkins  False  False   False    False     False     False
MIT           False  False   False    False     False     False
Northwestern  False  False   False    False     False     False
NotreDame     False  False   False    False     False     False
PennState     False  False   False    False     False     False
Princeton     False  False   False    False     False     False
Purdue        False  False   False    False     False     False
Stanford      False  False   False    False     False     False
TexasA&M      False  False   False    False     False     False
UCBerkeley    False  False   False    False     False     False
UChicago      False  False   False    False     False     False
UMichigan     False  False   False    False     False     False
UPenn         False  False   False    False     False     False
UVA           False  False   False    False     False     False
UWisconsin    False  False   False    False     False     False
Yale          False  False   False    False     False     False

In [62]:
dnull = [ [1,2,3,'M',7],
         [np.nan,5,6,np.nan,7],
         [8,np.nan,9,'F',10],
         [np.nan,np.nan,np.nan,'M',11] 
        ]

dframe = pd.DataFrame(dnull, columns=['a','b','c','d','e'])
dframe

     a    b    c    d   e
0  1.0  2.0  3.0    M   7
1  NaN  5.0  6.0  NaN   7
2  8.0  NaN  9.0    F  10
3  NaN  NaN  NaN    M  11

In [63]:
dframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       2 non-null      float64
 1   b       2 non-null      float64
 2   c       3 non-null      float64
 3   d       3 non-null      str
 4   e       4 non-null      int64
dtypes: float64(3), int64(1), str(1)
memory usage: 296.0 bytes

In [64]:
dframe.isna()

       a      b      c      d      e
0  False  False  False  False  False
1   True  False  False   True  False
2  False   True  False  False  False
3   True   True   True  False  False

#### Handling missing/null values

In [65]:
dframe.isna().sum()

a    2
b    2
c    1
d    1
e    0
dtype: int64

In [66]:
#### Option a: Drop rows containing null values

In [67]:
dframe_clean = dframe.dropna(
    #inplace=True
)

In [68]:
dframe

     a    b    c    d   e
0  1.0  2.0  3.0    M   7
1  NaN  5.0  6.0  NaN   7
2  8.0  NaN  9.0    F  10
3  NaN  NaN  NaN    M  11

In [69]:
dframe_clean

     a    b    c  d  e
0  1.0  2.0  3.0  M  7

#### Option b: Replace null values

In [70]:
avg_a = dframe['a'].mean()
avg_b = dframe['b'].mean()
avg_c = dframe['c'].mean()
avg_a, avg_b,avg_c

(np.float64(4.5), np.float64(3.5), np.float64(6.0))

In [71]:
dframe['d'].mode()

0    M
Name: d, dtype: str

In [72]:
mode_d = dframe['d'].mode()[0]
mode_d

'M'

In [73]:
dframe.fillna(
    {
        'a': avg_a,
        'b': avg_b,
        'c': avg_c,
        'd':mode_d
    }, 
    #inplace=True
)

     a    b    c  d   e
0  1.0  2.0  3.0  M   7
1  4.5  5.0  6.0  M   7
2  8.0  3.5  9.0  F  10
3  4.5  3.5  6.0  M  11

In [74]:
dframe

     a    b    c    d   e
0  1.0  2.0  3.0    M   7
1  NaN  5.0  6.0  NaN   7
2  8.0  NaN  9.0    F  10
3  NaN  NaN  NaN    M  11

#### Dropping rows and columns

In [75]:
d1 = [[1,2,3],[4,5,6],[7,8,9]]
df = pd.DataFrame(d1,columns=['pop','year','num'],index =['SF','LA','NY'])
df

    pop  year  num
SF    1     2    3
LA    4     5    6
NY    7     8    9

In [76]:
df.drop('LA', 
        axis=0  # default,
        #inplace=True
       )

    pop  year  num
SF    1     2    3
NY    7     8    9

In [77]:
df.drop('year', axis=1,
        #inplace=True
       )

    pop  num
SF    1    3
LA    4    6
NY    7    9

#### Handling Duplicates

In [78]:
ddup = pd.DataFrame({'col1':['A','A','B','B','B'],'col2':[2,2,2,3,3]})
ddup

  col1  col2
0    A     2
1    A     2
2    B     2
3    B     3
4    B     3

In [79]:
ddup.duplicated()

0    False
1     True
2    False
3    False
4     True
dtype: bool

In [80]:
ddup.drop_duplicates(
    #inplace=True
)

  col1  col2
0    A     2
2    B     2
3    B     3

In [81]:
ddup.drop_duplicates(
    #inplace=True,
    ignore_index=True
)

  col1  col2
0    A     2
1    B     2
2    B     3

### Combining Dataframes

In [82]:
d1 = [[1,2,3],[4,5,6]]
df1 = pd.DataFrame(d1,columns=['a','b','c'])


d2 = [[10,20,30],[40,50,60]]
df2 = pd.DataFrame(d2,columns=['d','e','f'])


d3 = [[11,22,33],[44,55,66]]
df3 = pd.DataFrame(d3,columns=['a','b','c'])

#### join()

In [83]:
df1

   a  b  c
0  1  2  3
1  4  5  6

In [84]:
df2

    d   e   f
0  10  20  30
1  40  50  60

In [85]:
df1.join(df2)

   a  b  c   d   e   f
0  1  2  3  10  20  30
1  4  5  6  40  50  60

#### concat

In [86]:
df1

   a  b  c
0  1  2  3
1  4  5  6

In [87]:
df3

    a   b   c
0  11  22  33
1  44  55  66

In [88]:
# Matching Columns
pd.concat([df1,df3], ignore_index=True)

    a   b   c
0   1   2   3
1   4   5   6
2  11  22  33
3  44  55  66

In [89]:
# Columns not matching
pd.concat([df1,df2], ignore_index=True)

     a    b    c     d     e     f
0  1.0  2.0  3.0   NaN   NaN   NaN
1  4.0  5.0  6.0   NaN   NaN   NaN
2  NaN  NaN  NaN  10.0  20.0  30.0
3  NaN  NaN  NaN  40.0  50.0  60.0

#### merge()

##### When the joining column names are SAME in both dataframes

In [90]:
d1 = {'movieid':[1,2,3,4,5],
     'title':['3 Idiots','2 States','Leo','RRR','Pushpa']}
movies = pd.DataFrame(d1)


d2 = {
    'memid':[1,2,3,4],
    'name':['Tom','Tim','Jon','Jim'],
    'movieid':[1,np.nan,3,5]
}
members=pd.DataFrame(d2)

In [91]:
movies

   movieid     title
0        1  3 Idiots
1        2  2 States
2        3       Leo
3        4       RRR
4        5    Pushpa

In [92]:
members

   memid name  movieid
0      1  Tom      1.0
1      2  Tim      NaN
2      3  Jon      3.0
3      4  Jim      5.0

In [93]:
# Records common to botha dataframes
# Show all movies that have been rented and the members who have rented the movies
pd.merge(movies,members, on='movieid', how='inner')

   movieid     title  memid name
0        1  3 Idiots      1  Tom
1        3       Leo      3  Jon
2        5    Pushpa      4  Jim

In [94]:
# Show ALL movies I have , if any member has rented it, show their details also
pd.merge(movies,members, on='movieid', how='left')

   movieid     title  memid name
0        1  3 Idiots    1.0  Tom
1        2  2 States    NaN  NaN
2        3       Leo    3.0  Jon
3        4       RRR    NaN  NaN
4        5    Pushpa    4.0  Jim

In [95]:
# Show ALL members and the movies they have rented
pd.merge(movies,members, on='movieid', how='right')

   movieid     title  memid name
0      1.0  3 Idiots      1  Tom
1      NaN       NaN      2  Tim
2      3.0       Leo      3  Jon
3      5.0    Pushpa      4  Jim

In [96]:
pd.merge(movies,members, on='movieid', how='outer')

   movieid     title  memid name
0      1.0  3 Idiots    1.0  Tom
1      2.0  2 States    NaN  NaN
2      3.0       Leo    3.0  Jon
3      4.0       RRR    NaN  NaN
4      5.0    Pushpa    4.0  Jim
5      NaN       NaN    2.0  Tim

##### When the joining column names are DIFFERENT in both dataframes

In [97]:
d1 = {'id':[1,2,3,4,5],
     'title':['3 Idiots','2 States','Leo','RRR','Pushpa']}
movies2 = pd.DataFrame(d1)


d2 = {
    'memid':[1,2,3,4],
    'name':['Tom','Tim','Jon','Jim'],
    'movieid':[1,np.nan,3,5]
}
members2=pd.DataFrame(d2)

In [98]:
movies2

   id     title
0   1  3 Idiots
1   2  2 States
2   3       Leo
3   4       RRR
4   5    Pushpa

In [99]:
members2

   memid name  movieid
0      1  Tom      1.0
1      2  Tim      NaN
2      3  Jon      3.0
3      4  Jim      5.0

In [100]:
pd.merge(movies2,members2, left_on='id',right_on='movieid', how='inner')

   id     title  memid name  movieid
0   1  3 Idiots      1  Tom      1.0
1   3       Leo      3  Jon      3.0
2   5    Pushpa      4  Jim      5.0

#### Grouping Records

In [101]:
salaries = pd.read_csv('Salaries.csv')
salaries.head()

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   20       20  Male  122400
2  AssocProf          A   20       17  Male   81285
3       Prof          B   23       23  Male  134778
4   AsstProf          B    1        0  Male   88000

In [102]:
salaries.shape

(51, 6)

In [103]:
salaries['rank'].nunique()

3

In [104]:
salaries['rank'].unique()

<ArrowStringArray>
['Prof', 'AssocProf', 'AsstProf']
Length: 3, dtype: str

In [105]:
salaries['rank'].value_counts()

rank
Prof         26
AsstProf     16
AssocProf     9
Name: count, dtype: int64

In [106]:
salaries['discipline'].nunique()

2

In [107]:
salaries['discipline'].unique()

<ArrowStringArray>
['B', 'A']
Length: 2, dtype: str

In [108]:
salaries['discipline'].value_counts()

discipline
B    28
A    23
Name: count, dtype: int64

In [109]:
rank_grp = salaries.groupby('rank')
rank_grp

In [110]:
for group in rank_grp:
    print(group)
    print('_'*60)

('AssocProf',          rank discipline  phd  service     sex  salary
2   AssocProf          A   20       17    Male   81285
17  AssocProf          B    9        7    Male  107008
19  AssocProf          B   12        8    Male  119800
23  AssocProf          A   13        8  Female   74830
26  AssocProf          B   11       11  Female  103613
34  AssocProf          B   12       10  Female  103994
37  AssocProf          A   26       24  Female   73300
44  AssocProf          B   12        9  Female   71065
47  AssocProf          B   19        6  Female  104542)
____________________________________________________________
('AsstProf',         rank discipline  phd  service     sex  salary
4   AsstProf          B    1        0    Male   88000
6   AsstProf          B    8        3    Male   75044
7   AsstProf          B    4        0    Male   92000
10  AsstProf          B    4        4    Male   92000
12  AsstProf          A    4        2    Male   73000
13  AsstProf          A    2        0    Male   85000
15  AsstProf          B    7        2    Male   91300
21  AsstProf          B    4        3    Male   91000
25  AsstProf          B   11        3  Female   74692
28  AsstProf          B   10        5  Female   97032
31  AsstProf          A    5        3  Female   73500
32  AsstProf          A    3        1  Female   72500
35  AsstProf          B    3        3  Female   92000
39  AsstProf          A    7        6  Female   63100
41  AsstProf          A    4        2  Female   77500
43  AsstProf          A    8        3  Female   78500)
____________________________________________________________
('Prof',     rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   20       20    Male  122400
3   Prof          B   23       23    Male  134778
5   Prof          B   17        3    Male  150480
8   Prof          A   19        7    Male  107300
9   Prof          A   29       27    Male  150500
11  Prof          A   33       30    Male  103106
14  Prof          A   30       23    Male   91100
16  Prof          B   21       20    Male  123683
18  Prof          B   22       21    Male  155750
20  Prof          B   45       45    Male  146856
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
27  Prof          B   17       17  Female  111512
29  Prof          B   20       14  Female  127512
30  Prof          A   12        0  Female  105000
33  Prof          B   36       26  Female  144651
36  Prof          A   29       27  Female   91000
38  Prof          A   36       19  Female  117555
40  Prof          A   17       11  Female   90450
42  Prof          A   28        7  Female  116450
45  Prof          B   24       15  Female  161101
46  Prof          B   18       10  Female  105450
48  Prof          B   17       17  Female  124312
49  Prof          A   28       14  Female  109954
50  Prof          A   23       15  Female  109646)
____________________________________________________________

In [111]:
for label,records in rank_grp:
    print(label)
    print('_'*60)

AssocProf
____________________________________________________________
AsstProf
____________________________________________________________
Prof
____________________________________________________________

In [112]:
for label,records in rank_grp:
    print(records)
    print('_'*60)

         rank discipline  phd  service     sex  salary
2   AssocProf          A   20       17    Male   81285
17  AssocProf          B    9        7    Male  107008
19  AssocProf          B   12        8    Male  119800
23  AssocProf          A   13        8  Female   74830
26  AssocProf          B   11       11  Female  103613
34  AssocProf          B   12       10  Female  103994
37  AssocProf          A   26       24  Female   73300
44  AssocProf          B   12        9  Female   71065
47  AssocProf          B   19        6  Female  104542
____________________________________________________________
        rank discipline  phd  service     sex  salary
4   AsstProf          B    1        0    Male   88000
6   AsstProf          B    8        3    Male   75044
7   AsstProf          B    4        0    Male   92000
10  AsstProf          B    4        4    Male   92000
12  AsstProf          A    4        2    Male   73000
13  AsstProf          A    2        0    Male   85000
15  AsstProf          B    7        2    Male   91300
21  AsstProf          B    4        3    Male   91000
25  AsstProf          B   11        3  Female   74692
28  AsstProf          B   10        5  Female   97032
31  AsstProf          A    5        3  Female   73500
32  AsstProf          A    3        1  Female   72500
35  AsstProf          B    3        3  Female   92000
39  AsstProf          A    7        6  Female   63100
41  AsstProf          A    4        2  Female   77500
43  AsstProf          A    8        3  Female   78500
____________________________________________________________
    rank discipline  phd  service     sex  salary
0   Prof          B   56       49    Male  186960
1   Prof          A   20       20    Male  122400
3   Prof          B   23       23    Male  134778
5   Prof          B   17        3    Male  150480
8   Prof          A   19        7    Male  107300
9   Prof          A   29       27    Male  150500
11  Prof          A   33       30    Male  103106
14  Prof          A   30       23    Male   91100
16  Prof          B   21       20    Male  123683
18  Prof          B   22       21    Male  155750
20  Prof          B   45       45    Male  146856
22  Prof          A   39       36  Female  137000
24  Prof          B   25       25  Female  140096
27  Prof          B   17       17  Female  111512
29  Prof          B   20       14  Female  127512
30  Prof          A   12        0  Female  105000
33  Prof          B   36       26  Female  144651
36  Prof          A   29       27  Female   91000
38  Prof          A   36       19  Female  117555
40  Prof          A   17       11  Female   90450
42  Prof          A   28        7  Female  116450
45  Prof          B   24       15  Female  161101
46  Prof          B   18       10  Female  105450
48  Prof          B   17       17  Female  124312
49  Prof          A   28       14  Female  109954
50  Prof          A   23       15  Female  109646
____________________________________________________________

In [113]:
rank_grp.agg('mean',numeric_only=True )

                 phd    service         salary
rank
AssocProf  14.888889  11.111111   93270.777778
AsstProf    5.312500   2.500000   82260.500000
Prof       26.307692  20.038462  125561.615385

In [114]:
rank_grp.agg(['min','max'] )

          discipline     phd     service         sex       salary
                 min max min max     min max     min   max    min     max
rank
AssocProf          A   B   9  26       6  24  Female  Male  71065  119800
AsstProf           A   B   1  11       0   6  Female  Male  63100   97032
Prof               A   B  12  56       0  49  Female  Male  90450  186960

#### Sorting Records

In [115]:
edf

    eid    ename   job  salary
e1  100      Tom   Mgr    2500
e2  200     Mary  Pgmr    3700
e3  300     Kate    HR    4200
e4  400      Tim   Mgr    3200
e5  500      Jon  Pgmr    6400
e6  600  William    HR    4700

In [116]:
# Ascending Order
edf.sort_values(by='salary')

    eid    ename   job  salary
e1  100      Tom   Mgr    2500
e4  400      Tim   Mgr    3200
e2  200     Mary  Pgmr    3700
e3  300     Kate    HR    4200
e6  600  William    HR    4700
e5  500      Jon  Pgmr    6400

In [117]:
# Descending Order
edf.sort_values(by='salary', ascending=False)

    eid    ename   job  salary
e5  500      Jon  Pgmr    6400
e6  600  William    HR    4700
e3  300     Kate    HR    4200
e2  200     Mary  Pgmr    3700
e4  400      Tim   Mgr    3200
e1  100      Tom   Mgr    2500

In [118]:
edf.sort_index(ascending=False)

    eid    ename   job  salary
e6  600  William    HR    4700
e5  500      Jon  Pgmr    6400
e4  400      Tim   Mgr    3200
e3  300     Kate    HR    4200
e2  200     Mary  Pgmr    3700
e1  100      Tom   Mgr    2500